name: Test Libcute

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build
      run: make IS_DYNAMIC=false

    - name: Run test
      run: make test IS_DYNAMIC=false

